### ISSUE TITLE
Task list for Sensitivity estimations

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#5344]
After the discussions in #4718 and the prototype in by @registerrier in  #4712 , decided to implement our gammapy API with the new sensitivity estimation.
This can be done using (at least) 3 PRs. Please feel free to assign yourselves 

- [ ] Add a `Dataset.stat_sum_asimov` to get the stat for an Asimov dataset. Also add on `Datasets` for convenience  @AtreyeeS 
- [ ] Add optiional quantity `sensitivity` on `FluxPointsEstimator`, `TSMapEstimator`
- [ ] Also, adapt the `ParameterEstimator` to compute sensitivity
- [ ] Adapt the current `SensitivityEstimator` to use implementation from Cowan et al

**Comment by adonath** [comment]
Thanks @AtreyeeS, the plan looks very reasonable! I will not have time to implement anything myself in the coming weeks, but I can review PRs.

**Comment by registerrier** [comment]
After #5637 #5639 #5679 the first three points have been addressed. The remaining aspect is adapting the `SensitivityEstimator`

**Comment by bkhelifi** [comment]
To be linked with the discussion: https://github.com/gammapy/gammapy/discussions/5417

**Comment by AtreyeeS** [comment]
Can we put this in for 2.0? @registerrier @QRemy @bkhelifi ?

**Comment by AtreyeeS** [comment]
I think we should not modify the `SensitivityEstimator` as it conforms to the default sensitivity definitions for CTA (eg: what pyirf does), but create a new `JointSensitivityEstimator` (probably inheriting from the `FluxPointsEstimator`) to compute sensivity with the Cowan approach
