### ISSUE TITLE
Plotting issues in some tutorials

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#5531]
**Gammapy version**
dev

**Bug description**
I have scanned all tutorials to check whether they are any obvious rendering issues. Here are my returns:

- [x]  [spectral_analysis](https://docs.gammapy.org/dev/tutorials/analysis-1d/spectral_analysis.html#a-note-on-statistics): list is not correctly rendered, strange annotation about asymetric Gaussian, strange error for wstat in the first plot for the section. PR: #5534 
- [x]  [spectral_analysis_hli](https://docs.gammapy.org/dev/tutorials/analysis-1d/spectral_analysis_hli.html#exploration-of-the-fit-results): Two mask fit ranges are plotted, and 2 mask safe (but not in residuals as expected) (PR: #5543)
- [x]  Remove the test `print(psf_new == psf_assym)` in https://docs.gammapy.org/dev/tutorials/api/irfs.html#id2? PR: #5537
- [x]  [accessing-contents-of-a-dataset](https://docs.gammapy.org/dev/tutorials/api/datasets.html#accessing-contents-of-a-dataset): Adding c_bar will not hurt PR: #5537
- [x]  [lightcurves]( https://docs.gammapy.org/dev/tutorials/api/catalog.html#lightcurves): x-axis labels are not visible - margin issue. PR: #5561
- [x]  Plot margin issue in the covariance plot (e.g. https://docs.gammapy.org/dev/tutorials/api/fitting.html#sphx-glr-tutorials-api-fitting-py)  PR: #5537
- [x]  missing legends (as feared for the closed PR #5529 ) in https://docs.gammapy.org/dev/tutorials/analysis-3d/flux_profiles.html#plotting-results and for the following plots
    - [x]  the plot of LCs should be fixed to add legends (identical issue than previously mentioned) in ALL timing tutorials that need to be checked once per once
- [x] y-label on flux points disappears on doc rendering (appears correctly when running the script) in [Low Level API](https://docs.gammapy.org/dev/tutorials/starting/analysis_2.html#sphx-glr-tutorials-starting-analysis-2-py). PR: #5584

**Comment by QRemy** [comment]
> * the plot of LCs should be fixed to add legends (identical issue than previously mentioned) in ALL timing tutorials that need to be checked once per once

Not showing the legend by default is consistent with the current behaviour for flux poins.
one can just add plt.legend() with custom options afterward.

**Comment by QRemy** [comment]
> * strange error for wstat in the first plot for the section: https://docs.gammapy.org/dev/tutorials/analysis-1d/spectral_analysis.html#a-note-on-statistics

the strange error comes from the "distrib" stat_type, I would just remove it from this plot and show it only on the second one.

**Comment by bkhelifi** [comment]
> > * strange error for wstat in the first plot for the section: https://docs.gammapy.org/dev/tutorials/analysis-1d/spectral_analysis.html#a-note-on-statistics
> 
> the strange error comes from the "distrib" stat_type, I would just remove it from this plot and show it only on the second one.

Is there a bug? Removing something that does not look nice is a bit scary

**Comment by QRemy** [comment]
> > > * strange error for wstat in the first plot for the section: https://docs.gammapy.org/dev/tutorials/analysis-1d/spectral_analysis.html#a-note-on-statistics
> > 
> > 
> > the strange error comes from the "distrib" stat_type, I would just remove it from this plot and show it only on the second one.
> 
> Is there a bug? Removing something that does not look nice is a bit scary

yes resolved by #5534

**Comment by Astro-Kirsty** [comment]
> missing legends (as feared for the closed PR https://github.com/gammapy/gammapy/pull/5529 ) in https://docs.gammapy.org/dev/tutorials/analysis-3d/flux_profiles.html#plotting-results and for the following plots

So now we need to add a `plt.legend` in every case? This doesn't seem so good to me.

**Comment by Astro-Kirsty** [comment]
We cannot close yet, as we need to address the other plotting issues. 
Specifically about the removal of the `plt.legend`. If we wish to leave it as it is, we need to add `plt.legend` in a number of tutorials before we can close

**Comment by Astro-Kirsty** [comment]
Last outstanding for this issue:

> Handling the removal of the plt.legend. If we wish to leave it as it is, we need to add plt.legend in a number of tutorials before we can close
