### ISSUE TITLE
Enhance CI

### ISSUE THREAD

**Issue by MRegeard** [gammapy/gammapy#5587]
This PR summaries idea to enhance our CI:

- [x] Pre-commit CI. Ruff pre-commit hook is currently running in as the first step in the CI
- [x] Use [OpenAstronomy github action workflow](https://github.com/OpenAstronomy/github-actions-workflows) Done in #5708 
- [x] Preview docs in PR (see Sunpy PR), (I don't know yet how it is done)
- [x] Use labels to skip jobs. Done in #5938 
- [x] Cron test docstring example and rst file testcode (#5480). Done in #5773

**Comment by registerrier** [comment]
Note regarding preview docs: it is possible to upload the result of a github action with something like:
```
    - name: Upload HTML output
      uses: actions/upload-artifact@v3
      with:
        name: preview-doc-html
        path: _build/html/
```
this will export the html directory in the form of a zip file accessible from the job page.

**Comment by registerrier** [comment]
I think linkcheck should be removed from the docs build in the CI. It is long and never carefully checked.
I would be better to have it run on a scheduled docs build, and possibly make it fail in case of error.

**Comment by MRegeard** [comment]
@registerrier I agree, links are not changing a lot anyway, and even so, checking them let's say once a week should be enough !

**Comment by morcuended** [comment]
> Preview docs in PR (see Sunpy PR), (I don't know yet how it done)

They do it through readthedocs (https://docs.readthedocs.com/platform/stable/pull-requests.html)

**Comment by bkhelifi** [comment]
@morcuended and @natthan-pigoux, what is the status here?

**Comment by morcuended** [comment]
I think the only open point from the list above is evaluating the use of Circle CI. Maybe the use case for it is to do regression tests for plots in the docs. Other related topic is the pre-commit, you should make sure that it runs and apply for all the code (e.g. integrating with pre-commit.ci bot)
